# Generated by Django 6.0.6 on 2026-06-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='Soatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='directions.direction', verbose_name="Yo'nalish")),
                ('lecturers', models.ManyToManyField(blank=True, related_name='taught_modules', to='users.lecturerprofile', verbose_name="Ma'ruzachilar")),
            ],
            options={
                'verbose_name': "O'quv dastur va modul",
                'verbose_name_plural': "O'quv dasturlar va modullar",
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Dastur nomi')),
                ('file', models.FileField(upload_to='programs/%Y/%m/', verbose_name='Fayl (PDF/DOCX)')),
                ('academic_year', models.CharField(help_text='Masalan: 2024-2025', max_length=20, verbose_name="O'quv yili")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='directions.direction', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "O'quv dasturi",
                'verbose_name_plural': "O'quv dasturlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
