# Generated by Django 6.0.6 on 2026-06-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at'], 'verbose_name': "O'quv dastur va modul", 'verbose_name_plural': "O'quv dasturlar va modullar"},
        ),
    ]
