# Generated by Django 6.0.6 on 2026-06-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at'], 'verbose_name': "O'quv dastur va modul", 'verbose_name_plural': 'Modullar'},
        ),
    ]
