# Generated by Django 4.2.18 on 2026-07-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0006_module_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='direction',
        ),
        migrations.AddField(
            model_name='module',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='modules', to='directions.direction', verbose_name="Yo'nalishlar"),
        ),
    ]
