# Generated by Django 4.2.18 on 2026-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0009_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': "Yo'nalish ", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'ordering': ['-created_at'], 'verbose_name': "O'quv dasturi ", 'verbose_name_plural': "O'quv dasturlari"},
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Oquv yili'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
    ]
