# Generated by Django 4.2.18 on 2026-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ijrotask',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('overdue', "Muddati o'tgan")], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
