# Generated by Django 4.2.18 on 2026-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_remove_ijrotask_completed_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ijrotask',
            options={'ordering': ['deadline', 'status'], 'verbose_name': 'Ijro.gov.uz topshiriqlari', 'verbose_name_plural': 'Ijro.gov.uz topshiriqlari'},
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='assigned_by',
            field=models.CharField(max_length=200, verbose_name='Kim tomonidan'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qabul qilingan sana'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='deadline',
            field=models.DateField(verbose_name='Bajarish muddati'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='result',
            field=models.TextField(blank=True, verbose_name='Bajarilish natijasi'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('overdue', "Muddati o'tgan")], default='new', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='task_number',
            field=models.CharField(max_length=100, verbose_name='Topshiriq raqami'),
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nomi показателя'),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Holat'),
        ),
    ]
