# Generated by Django 4.2.7 on 2026-06-20 20:32

import apps.materials.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('presentation', 'Taqdimot'), ('video', 'Video'), ('program', "O'quv dasturi"), ('control_questions', 'Nazorat savollari'), ('additional', "Qo'shimcha material")], max_length=20, verbose_name='Turi')),
                ('file', models.FileField(upload_to=apps.materials.models.material_upload_path, verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Kurs')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yuklangan')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
