# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Material ', 'verbose_name_plural': 'Materiallar'},
        ),
    ]
