# Generated by Django 4.2.18 on 2026-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('document', 'Hujjat'), ('presentation', 'Taqdimot'), ('video', 'Video'), ('audio', 'Audio'), ('animation', 'Animatsiya'), ('test', 'Test'), ('program', "O'quv dasturi"), ('control_questions', 'Nazorat savollari'), ('additional', "Qo'shimcha material")], max_length=20, verbose_name='Turi'),
        ),
    ]
