# Generated by Django 4.2.18 on 2026-07-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date', '-certificate_number'], 'verbose_name': 'Sertifikat ', 'verbose_name_plural': 'Sertifikatlar'},
        ),
    ]
