# Generated by Django 4.2.18 on 2026-07-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date', '-certificate_number'], 'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
    ]
