# Generated by Django 6.0.6 on 2026-06-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_alter_module_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
