# Generated by Django 6.0.6 on 2026-06-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_delete_module'),
        ('users', '0015_alter_studentprofile_options_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='Soatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='directions.direction', verbose_name="Yo'nalish")),
                ('lecturers', models.ManyToManyField(blank=True, related_name='taught_modules', to='users.lecturerprofile', verbose_name="Ma'ruzachilar")),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'db_table': 'directions_module',
            },
        ),
    ]
