# Generated by Django 4.2.18 on 2026-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0005_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('nazariy', 'Nazariy (Теоретический)'), ('amaliy', 'Amaliy (Практический)')], default='nazariy', max_length=10, verbose_name='Dars turi'),
        ),
    ]
