# Generated by Django 4.2.18 on 2026-07-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0007_remove_module_direction_module_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('nazariy', 'Nazariy'), ('amaliy', 'Amaliy')], default='nazariy', max_length=10, verbose_name='Dars turi'),
        ),
    ]
