# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0008_alter_module_module_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Modul ', 'verbose_name_plural': 'Modullar'},
        ),
    ]
