# Generated by Django 6.0.6 on 2026-06-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Mavjud kurs', 'verbose_name_plural': 'Mavjud kurslar'},
        ),
    ]
