# Generated by Django 6.0.6 on 2026-06-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_topic_options_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Avtorizatsiyadan utgan guruh', 'verbose_name_plural': 'Avtorizatsiyadan utgan guruhlar'},
        ),
    ]
