# Generated by Django 6.0.6 on 2026-06-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Kursga yozilgan guruh', 'verbose_name_plural': 'Kursga yozilgan guruhlar'},
        ),
    ]
