# Generated by Django 6.0.6 on 2026-06-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_group_options'),
        ('users', '0011_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='Soatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.lecturerprofile', verbose_name="Ma'ruzachi")),
            ],
            options={
                'verbose_name': "O'quv dastur va modul",
                'verbose_name_plural': "O'quv dasturlar va modullar",
            },
        ),
    ]
