# Generated by Django 6.0.6 on 2026-06-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
