# Generated by Django 4.2.18 on 2026-07-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Maks. tinglovchilar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_groups', to='courses.course', verbose_name='Kurs')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='course_groups', through='courses.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Tinglovchilar')),
            ],
            options={
                'verbose_name': "O'quv guruhi ",
                'verbose_name_plural': "O'quv guruhlari",
                'db_table': 'courses_group',
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.academicgroup', verbose_name='Guruh'),
        ),
    ]
