# Generated by Django 4.2.18 on 2026-07-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_group_course_remove_group_students_and_more'),
        ('schedules', '0003_alter_schedule_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
