# Generated by Django 4.2.18 on 2026-07-09 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Макс. балл')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория KPI',
                'verbose_name_plural': 'Категории KPI',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KPIIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название показателя')),
                ('criterion', models.TextField(verbose_name='Критерий оценки')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Макс. балл')),
                ('measurement_unit', models.CharField(choices=[('count', 'Количество'), ('percent', 'Процент'), ('date', 'Срок'), ('boolean', 'Да/Нет')], max_length=50, verbose_name='Единица измерения')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Целевое значение')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='kpi.kpicategory')),
            ],
            options={
                'verbose_name': 'Показатель KPI',
                'verbose_name_plural': 'Показатели KPI',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Общий балл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет KPI',
                'verbose_name_plural': 'Отчеты KPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IjroTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=100, verbose_name='Номер поручения')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('assigned_by', models.CharField(max_length=200, verbose_name='От кого')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('overdue', 'Просрочено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('result', models.TextField(blank=True, verbose_name='Результат исполнения')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ijro_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поручение Ijro.gov.uz',
                'verbose_name_plural': 'Поручения Ijro.gov.uz',
                'ordering': ['deadline', 'status'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическое значение')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Полученный балл')),
                ('evidence', models.TextField(blank=True, verbose_name='Подтверждение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='kpi_attachments/', verbose_name='Приложение')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpiindicator')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_values', to='kpi.kpireport')),
            ],
            options={
                'verbose_name': 'Значение KPI',
                'verbose_name_plural': 'Значения KPI',
                'unique_together': {('report', 'indicator')},
            },
        ),
    ]
