# Generated by Django 4.2.18 on 2026-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_ijrotask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijrotask',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='ijrotask',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli (Ijro.uz)'),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli (Ijro.uz)'),
        ),
        migrations.AddField(
            model_name='kpiindicator',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='kpiindicator',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli (Ijro.uz)'),
        ),
        migrations.AddField(
            model_name='kpireport',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='kpireport',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli (Ijro.uz)'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli (Ijro.uz)'),
        ),
    ]
