# Generated by Django 4.2.18 on 2026-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_ijrotask_completed_file_ijrotask_incoming_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ijrotask',
            name='completed_file',
        ),
        migrations.RemoveField(
            model_name='ijrotask',
            name='incoming_file',
        ),
        migrations.RemoveField(
            model_name='kpicategory',
            name='completed_file',
        ),
        migrations.RemoveField(
            model_name='kpicategory',
            name='incoming_file',
        ),
        migrations.RemoveField(
            model_name='kpiindicator',
            name='completed_file',
        ),
        migrations.RemoveField(
            model_name='kpiindicator',
            name='incoming_file',
        ),
        migrations.RemoveField(
            model_name='kpireport',
            name='completed_file',
        ),
        migrations.RemoveField(
            model_name='kpireport',
            name='incoming_file',
        ),
        migrations.RemoveField(
            model_name='kpivalue',
            name='completed_file',
        ),
        migrations.RemoveField(
            model_name='kpivalue',
            name='incoming_file',
        ),
        migrations.AlterField(
            model_name='ijrotask',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('overdue', 'Просрочено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
