# Generated by Django 4.2.18 on 2026-07-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_alter_ijrotask_options_alter_ijrotask_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijrotask',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/completed/', verbose_name='Bajarilgan topshiriq fayli'),
        ),
        migrations.AddField(
            model_name='ijrotask',
            name='incoming_file',
            field=models.FileField(blank=True, null=True, upload_to='ijro_tasks/incoming/', verbose_name='Kiruvchi hujjat fayli'),
        ),
    ]
