# Generated by Django 4.2.18 on 2026-08-10 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0015_delete_group'),
        ('certificates', '0004_delete_announcement_alter_certificate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='Всего занятий')),
                ('counted_attendances', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Зачтённые посещения')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Посещаемость, %')),
                ('attendance_passed', models.BooleanField(default=False, verbose_name='Порог посещаемости пройден')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Результат экзамена, %')),
                ('exam_passed', models.BooleanField(default=False, verbose_name='Экзамен сдан')),
                ('retake_allowed', models.BooleanField(default=False, verbose_name='Пересдача разрешена')),
                ('retake_allowed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разрешения пересдачи')),
                ('retake_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Результат пересдачи, %')),
                ('retake_passed', models.BooleanField(default=False, verbose_name='Пересдача сдана')),
                ('eligible_for_certificate', models.BooleanField(default=False, verbose_name='Допущен к сертификату')),
                ('certificate_approved', models.BooleanField(default=False, verbose_name='Сертификат утверждён')),
                ('certificate_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения сертификата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_records', to='certificates.certificate', verbose_name='Выданный сертификат')),
                ('certificate_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates_assessment', to=settings.AUTH_USER_MODEL, verbose_name='Сертификат утвердил')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='courses.academicgroup', verbose_name='Учебная группа')),
                ('retake_allowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_retakes', to=settings.AUTH_USER_MODEL, verbose_name='Пересдачу разрешил')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to=settings.AUTH_USER_MODEL, verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Запись аттестации',
                'verbose_name_plural': 'Записи аттестации',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
