# Generated by Django 4.2.18 on 2026-08-14 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_delete_announcement_alter_certificate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_delete_group'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentrecord',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Attestatsiya yozuvi', 'verbose_name_plural': 'Attestatsiya yozuvlari'},
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='attendance_passed',
            field=models.BooleanField(default=False, verbose_name="Qatnashish chegarasi o'tildi"),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Qatnashish, %'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_records', to='certificates.certificate', verbose_name='Berilgan sertifikat'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='certificate_approved',
            field=models.BooleanField(default=False, verbose_name='Sertifikat tasdiqlandi'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='certificate_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='certificate_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates_assessment', to=settings.AUTH_USER_MODEL, verbose_name='Sertifikatni tasdiqlagan'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='counted_attendances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Hisobga olingan qatnashishlar'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='eligible_for_certificate',
            field=models.BooleanField(default=False, verbose_name='Sertifikatga tayyor'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='exam_passed',
            field=models.BooleanField(default=False, verbose_name='Imtihon topshirildi'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Imtihon natijasi, %'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='courses.academicgroup', verbose_name="O'quv guruhi"),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='retake_allowed',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirishga ruxsat berildi'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='retake_allowed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ruxsat berilgan sana'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='retake_allowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_retakes', to=settings.AUTH_USER_MODEL, verbose_name='Qayta topshirishga ruxsat bergan'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='retake_passed',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirish muvaffaqiyatli'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='retake_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Qayta topshirish natijasi, %'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to=settings.AUTH_USER_MODEL, verbose_name='Tinglovchi'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami darslar'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
    ]
