# Generated by Django 4.2.18 on 2026-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_passport_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
