# Generated by Django 6.0.6 on 2026-06-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_group_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Kursga yozilgan guruh', 'verbose_name_plural': 'Kursga yozilgan guruhlar'},
        ),
    ]
