# Generated by Django 6.0.6 on 2026-06-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Kursga oid mavzu', 'verbose_name_plural': 'Kursga oid mavzular'},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
    ]
