# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Mavjud kurs ', 'verbose_name_plural': 'Mavjud kurslar'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Kursga yozilish ', 'verbose_name_plural': 'Kursga yozilish'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Kursga yozilgan guruh ', 'verbose_name_plural': 'Kursga yozilgan guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Kursga oid mavzu ', 'verbose_name_plural': 'Kursga oid mavzular'},
        ),
    ]
