# Generated by Django 4.2.18 on 2026-07-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0003_alter_zoomaccount_options_alter_zoommeeting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoomaccount',
            options={'verbose_name': 'Zoom Hisob ', 'verbose_name_plural': 'Onlayn uchrashuv tashkil etish va Akkaunt sozlamalari'},
        ),
    ]
