# Generated by Django 4.2.7 on 2026-06-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'verbose_name': "Ma'ruzachi profili", 'verbose_name_plural': "Ma'ruzachi profillari"},
        ),
    ]
