# Generated by Django 4.2.7 on 2026-06-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lecturerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'verbose_name': "Ma'ruzachilar profili", 'verbose_name_plural': "Ma'ruzachilar profillari"},
        ),
    ]
