# Generated by Django 6.0.6 on 2026-06-21 18:10

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_lecturerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'verbose_name': "Ma'ruzachi profili", 'verbose_name_plural': "Ma'ruzachilar profillari"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='max_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_data',
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Ish tajribasi (yil)'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asosiy mutaxassisligi'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='working_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='Ish soatlari'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('director', 'Director'), ('lecturer', "Ma'ruzachi"), ('student', 'Tinglovchi')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='Soatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.lecturerprofile', verbose_name="Ma'ruzachi")),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['name'],
            },
        ),
    ]
