# Generated by Django 6.0.6 on 2026-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_lecturerprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['group', 'sequence_number'], 'verbose_name': 'Tinglovchi profili', 'verbose_name_plural': 'Tinglovchilar profillari'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district_power_supply',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Tuman elektr ta'minoti"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='final_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yakuniy bahosi'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name_qualification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Malaka oshiruvchilar (FIO)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guruhi'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='independent_study_topic',
            field=models.TextField(blank=True, null=True, verbose_name="Mustaqil ta'lim mavzusi"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasport'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualification_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Malaka oshirish muddati'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='regional_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hududiy filiali nomi'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sequence_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='T/R'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='xtm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='XTM'),
        ),
    ]
