# Generated by Django 6.0.6 on 2026-06-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'verbose_name': "Ma'ruzachi profili", 'verbose_name_plural': "Ma'ruzachilar"},
        ),
    ]
