# Generated by Django 6.0.6 on 2026-06-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_module_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
