# Generated by Django 6.0.6 on 2026-06-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Avtorizatsiyalangan foydalanuvchi', 'verbose_name_plural': 'Avtorizatsiyalangan foydalanuvchilar'},
        ),
    ]
