# Generated by Django 6.0.6 on 2026-06-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
    ]
