# Generated by Django 6.0.6 on 2026-06-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_studentprofile_options_delete_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Avtorizatsiyalangan foydalanuvchi', 'verbose_name_plural': "Avtorizatsiyadan o'tgan foydalanuvchilar"},
        ),
    ]
