# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Tinglovchi profili ', 'verbose_name_plural': 'Tinglovchilar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Avtorizatsiyalangan foydalanuvchi  ', 'verbose_name_plural': "Avtorizatsiyadan o'tgan foydalanuvchilar"},
        ),
    ]
