# Generated by Django 4.2.18 on 2026-07-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_studentrecord_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'ordering': ['full_name'], 'verbose_name': 'Tinglovchi', 'verbose_name_plural': "Ma'lumotlar bazasi"},
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['passport'], name='idx_studentrecord_passport'),
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['phone'], name='idx_studentrecord_phone'),
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['training_year', 'branch'], name='idx_studentrecord_year_branch'),
        ),
    ]
