# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_studentrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'ordering': ['full_name'], 'verbose_name': 'Tinglovchi  ', 'verbose_name_plural': "Ma'lumotlar bazasi"},
        ),
    ]
