# Generated by Django 4.2.18 on 2026-06-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'ordering': ['full_name'], 'verbose_name': 'Tinglovchi', 'verbose_name_plural': "Ma'lumotlar bazasi"},
        ),
    ]
