# Generated by Django 4.2.18 on 2026-07-06 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_alter_passport_nullable'),
        ('courses', '0015_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seriya')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sertifikat raqami')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR kod')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr/', verbose_name='QR rasm')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/', verbose_name='PDF fayl')),
                ('status', models.CharField(choices=[('issued', 'Berilgan'), ('revoked', 'Bekor qilingan'), ('duplicate', 'Dublikat'), ('draft', 'Loyiha')], default='draft', max_length=20, verbose_name='Holat')),
                ('registry_number', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ro'yxat raqami (MYHT)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='groups.studentrecord', verbose_name='Tinglovchi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issue_date', '-certificate_number'],
                'indexes': [models.Index(fields=['certificate_number'], name='idx_cert_number'), models.Index(fields=['qr_code'], name='idx_cert_qr'), models.Index(fields=['student', 'course'], name='idx_cert_student_course')],
            },
        ),
    ]
