# Generated by Django 4.2.7 on 2026-06-20 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('type', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Bir nechta to'g'ri javob"), ('open', 'Ochiq javob'), ('true_false', "To'g'ri/Noto'g'ri")], max_length=15, verbose_name='Savol turi')),
                ('options', models.JSONField(default=list, help_text="Single/multiple uchun variantlar massivi. Open uchun bo'sh massiv.", verbose_name='Javob variantlari')),
                ('correct_answer', models.TextField(blank=True, help_text="Single uchun to'g'ri variant. Multiple uchun to'g'ri variantlar massivi. Open uchun matn.", verbose_name="To'g'ri javob")),
                ('score', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan')),
            ],
            options={
                'verbose_name': 'Imtihon savoli',
                'verbose_name_plural': 'Imtihon savollari',
                'ordering': ['course', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Umumiy ball')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Maksimal ball')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Topshirilgan')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('passing_score_percentage', models.PositiveIntegerField(default=70, verbose_name="O'tish foizi")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='courses.course', verbose_name='Kurs')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Tinglovchi')),
            ],
            options={
                'verbose_name': 'Test sessiyasi',
                'verbose_name_plural': 'Test sessiyalari',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Tinglovchining javobi')),
                ('score_obtained', models.PositiveIntegerField(default=0, verbose_name='Olingan ball')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_results', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan baholangan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examquestion', verbose_name='Savol')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='Tinglovchi')),
            ],
            options={
                'verbose_name': 'Imtihon natijasi',
                'verbose_name_plural': 'Imtihon natijalari',
                'unique_together': {('student', 'question')},
            },
        ),
    ]
