# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['course', 'id'], 'verbose_name': 'Imtihon savoli ', 'verbose_name_plural': 'Imtihon savollari'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Imtihon natijasi ', 'verbose_name_plural': 'Imtihon natijalari'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Test sessiyasi ', 'verbose_name_plural': 'Test sessiyalari'},
        ),
    ]
