# Generated by Django 4.2.18 on 2026-08-10 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_alter_examquestion_options_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='approved_by_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retake_results', to=settings.AUTH_USER_MODEL, verbose_name='Qayta topshirishni tasdiqlagan direktor'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Urinish raqami'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_retake',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirish'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Urinish raqami'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='is_retake',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirish sessiyasi'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'question', 'attempt_number')},
        ),
    ]
