# Generated by Django 4.2.7 on 2026-06-20 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('date_end', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Auditoriya')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name="E'lon qilingan sana")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.group', verbose_name='Guruh')),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_schedules', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schedules', to=settings.AUTH_USER_MODEL, verbose_name="Kim tomonidan e'lon qilingan")),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Qatnashgan'), ('absent', 'Qatnashmagan'), ('late', 'Kechikkan'), ('excused', 'Uzrli sabab')], default='absent', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan belgilangan')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedules.schedule', verbose_name='Dars')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Tinglovchi')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date_start', 'date_end'], name='schedules_s_date_st_a6d19d_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['group', 'date_start'], name='schedules_s_group_i_f09ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['lecturer', 'date_start'], name='schedules_s_lecture_fed898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule', 'student')},
        ),
    ]
