# Generated by Django 4.2.18 on 2026-07-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_group_course_remove_group_students_and_more'),
        ('schedules', '0002_alter_attendance_options_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.academicgroup', verbose_name='Guruh'),
        ),
    ]
