# Generated by Django 4.2.18 on 2026-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_schedule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Tasdiqlanmagan'), ('published', "E'lon qilingan"), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati'),
        ),
    ]
