# Generated by Django 4.2.18 on 2026-07-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
        ('courses', '0012_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('account_id', models.CharField(max_length=100, unique=True, verbose_name='Account ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoom Hisob',
                'verbose_name_plural': 'Zoom Hisoblar',
            },
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.CharField(blank=True, help_text='Zoom tomonidan berilgan ID', max_length=100, verbose_name='Zoom Meeting ID')),
                ('zoom_join_url', models.URLField(blank=True, help_text='Talabalar uchun havola', verbose_name="Qo'shilish URL")),
                ('zoom_start_url', models.URLField(blank=True, help_text="O'qituvchi uchun havola", verbose_name='Boshlash URL')),
                ('zoom_password', models.CharField(blank=True, max_length=50, verbose_name='Parol')),
                ('topic', models.CharField(max_length=300, verbose_name='Mavzu')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)')),
                ('recurrence', models.CharField(choices=[('none', "Yo'q"), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], default='none', max_length=20, verbose_name='Takrorlanish')),
                ('waiting_room', models.BooleanField(default=True, verbose_name='Kutish xonasi')),
                ('join_before_host', models.BooleanField(default=False, verbose_name="Hostdan oldin qo'shilish")),
                ('mute_upon_entry', models.BooleanField(default=True, verbose_name="Kirganda ovozni o'chirish")),
                ('auto_recording', models.CharField(choices=[('cloud', 'Bulutda'), ('local', 'Lokal'), ('none', "Yo'q")], default='cloud', max_length=20, verbose_name='Avtomatik yozish')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('live', 'Jonli efirda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='courses.course', verbose_name='Kurs')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='schedules.schedule', verbose_name='Dars jadvali')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('zoom_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoom_integration.zoomaccount', verbose_name='Zoom hisob')),
            ],
            options={
                'verbose_name': 'Zoom Uchrashuv',
                'verbose_name_plural': 'Zoom Uchrashuvlar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ZoomRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_url', models.URLField(verbose_name='Yozish URL')),
                ('download_url', models.URLField(blank=True, verbose_name='Yuklab olish URL')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_mb', models.FloatField(default=0)),
                ('recording_type', models.CharField(choices=[('shared_screen', 'Ekran'), ('speaker_view', 'Spiker'), ('gallery_view', 'Galereya'), ('audio_only', 'Faqat audio')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='zoom_integration.zoommeeting')),
            ],
            options={
                'verbose_name': 'Zoom Yozuv',
                'verbose_name_plural': 'Zoom Yozuvlar',
            },
        ),
        migrations.CreateModel(
            name='ZoomMeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zoom_integration.zoommeeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
            },
        ),
    ]
