# Generated by Django 4.2.18 on 2026-07-04 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoom_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoomaccount',
            options={'verbose_name': 'Zoom Hisob ', 'verbose_name_plural': 'Zoom Hisoblar'},
        ),
        migrations.AlterModelOptions(
            name='zoommeeting',
            options={'ordering': ['-start_time'], 'verbose_name': 'Zoom Uchrashuv ', 'verbose_name_plural': 'Zoom Uchrashuvlar'},
        ),
        migrations.AlterModelOptions(
            name='zoommeetingparticipant',
            options={'verbose_name': 'Ishtirokchi ', 'verbose_name_plural': 'Ishtirokchilar'},
        ),
        migrations.AlterModelOptions(
            name='zoomrecording',
            options={'verbose_name': 'Zoom Yozuv ', 'verbose_name_plural': 'Zoom Yozuvlar'},
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='auto_recording',
            field=models.CharField(choices=[('cloud', 'Bulutda'), ('local', 'Lokal'), ('none', 'Yoq')], default='cloud', max_length=20, verbose_name='Avtomatik yozish'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='join_before_host',
            field=models.BooleanField(default=False, verbose_name='Hostdan oldin qoshilish'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='mute_upon_entry',
            field=models.BooleanField(default=True, verbose_name='Kirganda ovozni ochirish'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Yoq'), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], default='none', max_length=20, verbose_name='Takrorlanish'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Oqituvchi '),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='zoom_join_url',
            field=models.URLField(blank=True, verbose_name='Qoshilish URL'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zoom Meeting ID'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='zoom_start_url',
            field=models.URLField(blank=True, verbose_name='Boshlash URL'),
        ),
        migrations.AlterField(
            model_name='zoommeetingparticipant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Toliq ism'),
        ),
    ]
