# Generated by Django 4.2.18 on 2026-07-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0002_alter_zoomaccount_options_alter_zoommeeting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoomaccount',
            options={'verbose_name': 'Zoom Hisob ', 'verbose_name_plural': 'Zoom akkauntlar'},
        ),
        migrations.AlterModelOptions(
            name='zoommeeting',
            options={'ordering': ['-start_time'], 'verbose_name': 'Zoom Uchrashuv ', 'verbose_name_plural': 'Zoom orqali onlayn uchrashuv'},
        ),
        migrations.AlterModelOptions(
            name='zoomrecording',
            options={'verbose_name': 'Zoom Yozuv ', 'verbose_name_plural': 'Onlayn uchrashuvlar yozuvlari'},
        ),
    ]
