# Generated by Django 4.2.18 on 2026-06-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Yil nomi')),
            ],
            options={
                'verbose_name': "O'quv yili",
                'verbose_name_plural': "O'quv yillari",
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtm', models.CharField(blank=True, max_length=100, null=True, verbose_name='XTM kodi')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Malaka oshiruvchi (FIO)')),
                ('position', models.CharField(blank=True, max_length=300, null=True, verbose_name='Lavozimi')),
                ('passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasport')),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True, verbose_name="Tug'ilgan sanasi")),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guruhi')),
                ('branch', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hududiy filial nomi')),
                ('district_power', models.CharField(blank=True, max_length=200, null=True, verbose_name="Tuman elektr ta'minoti")),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yakuniy bahosi')),
                ('topic', models.TextField(blank=True, null=True, verbose_name="Mustaqil ta'lim mavzusi")),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Malaka oshirish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('training_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.trainingyear', verbose_name="O'quv yili")),
            ],
            options={
                'verbose_name': 'Tinglovchi',
                'verbose_name_plural': "Ma'lumotlar bazasi",
                'ordering': ['id'],
            },
        ),
    ]
