# Generated by Django 4.2.18 on 2026-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Davomat ', 'verbose_name_plural': 'Davomat'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date_start'], 'verbose_name': 'Dars ', 'verbose_name_plural': 'Darslar'},
        ),
    ]
