# Generated by Django 4.2.18 on 2026-08-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tinglovchi darsda necha daqiqa qatnashgani. Kechikishlarni hisobga olish uchun ishlatiladi.', null=True, verbose_name='Qatnashgan daqiqalar'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90, help_text="Davomatni hisoblash uchun darsning to'liq davomiyligi (daqiqalarda).", verbose_name='Dars davomiyligi (daqiqa)'),
        ),
    ]
