# Generated by Django 6.0.6 on 2026-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('director', 'Direktor'), ('department_head', "Bo'lim boshlig'i"), ('methodist', 'Metodist'), ('lecturer', "Ma'ruzachi"), ('student', 'Tinglovchi')], default='student', max_length=20, verbose_name='Rol'),
        ),
    ]
