# Generated by Django 6.0.6 on 2026-06-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_lecturerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': "O'quv dastur va modul", 'verbose_name_plural': "O'quv dasturlar va modullar"},
        ),
    ]
