# Generated by Django 6.0.6 on 2026-06-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'Modullar'},
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
