# Generated by Django 6.0.6 on 2026-06-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Tinglovchi profili', 'verbose_name_plural': 'Tinglovchilar'},
        ),
    ]
