# Generated by Django 4.2.18 on 2026-07-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Avtorizatsiyalangan foydalanuvchi ', 'verbose_name_plural': "Avtorizatsiyadan o'tgan foydalanuvchilar"},
        ),
    ]
